### ISSUE TITLE
Error in Reserve Room (404 on api)

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/hotel-website-vkirirom.com#344] opened 2020-01-28 04:27 UTC
**Describe the bug**
attempting to reserve a room on develop.vkirirom.com , cannot complete, "Error in Reserve Room". There is a console error attempting to hit (404) https://stagingapi.whynot.earth/api/v0/reservations/roomtype/55/reserve when clicking booking. 

**To Reproduce**
1. Attempt to book Bell tent for 2 nights (jan 30-feb1), 2 guests. reserve.
2. See error
3. 404 error in console on https://stagingapi.whynot.earth/api/v0/reservations/roomtype/55/reserve

**Expected behavior**
Successful booking and thank you page. emails fire.

**Screenshots**
![image](https://user-images.githubusercontent.com/5694308/73235367-c4d45f00-41c0-11ea-84c0-ef9a0fc4c081.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version latest

**Comment by mort3za** [comment] 2020-01-28 20:34
@paulchrisluke This is handled in frontend. Better to clone issue to meredith-core.

**Comment by ctyar** [comment] 2020-02-14 03:46
Duplicate of https://github.com/whynotearth/meredith-core/issues/72

**Closed by ctyar** 2020-02-14 03:46 UTC
Labels: bug
